### ISSUE TITLE
set listen Address 0.0.0.0, use public ip to access

### ISSUE THREAD

**Issue by riichg5** [hughperkins/peaceful-pie#4]
i set listen Address 0.0.0.0, use public ip to access, but got 400 response, Bad Request (Invalid host)

use [peaceful-pie](https://github.com/hughperkins/peaceful-pie)  v1.4.0

![image](https://github.com/hughperkins/peaceful-pie/assets/4560963/e15cbd10-cd8e-4630-a7d6-010f662e921e)

<img width="872" alt="image" src="https://github.com/hughperkins/peaceful-pie/assets/4560963/500e3ff5-9938-417b-b8de-5302d6211d9c">

<img width="787" alt="image" src="https://github.com/hughperkins/peaceful-pie/assets/4560963/9efcc530-c252-4a8c-b71a-2dea56050226">

**Comment by hughperkins** [comment]
400 means that your request is reaching the server, so the IP address is ok. 400 means there is something wrong with your request. It is malformed in some way. But it's not an IP address issue. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

**Comment by hughperkins** [comment]
Oh, just looked at your second screenshot. Hmmm.

**Comment by hughperkins** [comment]
Oh right, I remember now. Unity is the *server*, not the client. Your python executable is the server.

So... you cannot use 0.0.0.0 as the ip address when calling a server. 0.0.0.0 is not a valid ip address. At least, it means "all ip addresses". And how can you send a message to "all ip addresses"?

The connection is from Unity to the python process. So you need to find a way for Unity to communicate to the python process.

The easiest way is likely to run the python process on the same instance that you are running the Unity processes. That's what I was doing.

Otherwise, you could use ssh tunneling, to create a tunnel from the instance to your local machine, where there python service is running. More complicatd though.

Do you have any reasons not to run the python service on the insance itself?

**Comment by riichg5** [comment]
Thank you for your patient reply.

Unity is the server, so it bind 0.0.0.0, this unity program will be run in a windows server, and python will be deploy to another linux server, this is why this agent must bind 0.0.0.0.

I need a lot of unity  program server, they are the game environments, I will use [MCTS](https://en.wikipedia.org/wiki/Monte_Carlo_tree_search) algorithm to evaluating the game difficulty.

**Comment by hughperkins** [comment]
To be honest, I don't remember which is the server. Would need to check the code... You might be right that unity is the server, in which case 0.0.0.0 would make sense, as you say. Yeah, unity is probably the server. Hmmm.

**Comment by hughperkins** [comment]
But, if unity is the server, why am I adding a config for IP address on the server? Pondering.

**Comment by hughperkins** [comment]
Oh it does clearly say "listen address". So yeah, probably the server...

**Comment by riichg5** [comment]
The problem has been solved.
![image](https://github.com/hughperkins/peaceful-pie/assets/4560963/7b81da38-199a-414a-98d0-8c04d1b463f3)
set Listen Address to +,so unity can accept connection from another device. 

[peaceful-pie](https://github.com/hughperkins/peaceful-pie/tree/main)/[PeacefulPie](https://github.com/hughperkins/peaceful-pie/tree/main/PeacefulPie)
/NetManager.cs
the code use HttpListener

`		listener = new HttpListener();
		listener.Prefixes.Add($"http://{ListenAddress}:{ListenPort}/");`

I found the solution at then end of this web page. https://stackoverflow.com/questions/27770730/400-bad-request-invalid-host-using-simple-webserver-in-c-sharp

**Comment by hughperkins** [comment]
Thank you very much :) 🎉

**Comment by riichg5** [comment]
> Thank you very much :) 🎉

You're welcome! 😊
